FROM node:slim AS dev

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY . .

CMD [ "npm", "run", "dev" ]

# docker build -t express .  
# docker run -it --rm --network todos-network -p 3000:3000 --name  express express:latest