# Dockerfile
FROM redis:7.4.2

COPY redis.conf /usr/local/etc/redis/redis.conf

EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# docker run  --network todos-network -v todos-redis-data:/data --name redis -p 6379:6379 redis:latest